import e from"@babel/runtime-corejs3/helpers/slicedToArray";import r from"@babel/runtime-corejs3/core-js-stable/set-timeout";import n from"@babel/runtime-corejs3/core-js-stable/instance/for-each";import t from"@babel/runtime-corejs3/core-js-stable/object/entries";import{useState as o,useRef as c,useCallback as i,useEffect as u,useMemo as l}from"react";import{findDOMNode as a,createPortal as s}from"react-dom";
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */function f(e,r){var n={};for(var t in e)Object.prototype.hasOwnProperty.call(e,t)&&r.indexOf(t)<0&&(n[t]=e[t]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var o=0;for(t=Object.getOwnPropertySymbols(e);o<t.length;o++)r.indexOf(t[o])<0&&Object.prototype.propertyIsEnumerable.call(e,t[o])&&(n[t[o]]=e[t[o]])}return n}export default function(){var d=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{},m=d.closeOnEsc,v=void 0===m||m,p=d.closeOnOutsideClick,b=void 0===p||p,E=d.bindTo,O=d.isVisible,y=void 0!==O&&O,j=d.onClose,h=d.onOpen,g=d.onPortalClick,w=f(d,["closeOnEsc","closeOnOutsideClick","bindTo","isVisible","onClose","onOpen","onPortalClick"]),L=o(y),C=e(L,2),P=C[0],T=C[1],k=c(P),x=i((function(e){k.current=e,T(e)}),[]),H=c(),M=c(document.createElement("div"));u((function(){M.current||(M.current=document.createElement("div"))}),[M]);var S=l((function(){return E&&a(E)||document.body}),[E]),V=i((function(e){var r=e.children;return null!=M.current?s(r,M.current):null}),[M]),A=c({}),I=function(e){if(!e)return{portal:M,targetEl:H,event:e};var r=e||{};r.persist&&r.persist(),r.portal=M,r.targetEl=H,r.event=e;var n=e.currentTarget;return!H.current&&n&&n!==document&&(H.current=r.currentTarget),r},R=i((function(e){var n=I(e);if(null==H.current)throw r((function(){return x(!0)}),0),Error("error");h&&h(n),x(!0)}),[M,x,H,h]),W=i((function(e){var r=I(e);j&&k.current&&j(r),k.current&&x(!1)}),[j,x]),q=i((function(e){return"Escape"===e.key&&v?W(e):void 0}),[v,W]),z=i((function(e){var r=function(r){return r.current.contains(e.target)};r(M)||0!==e.button||!k.current||r(H)||b&&W(e)}),[W,b,M]),B=i((function(e){if(M.current instanceof HTMLElement){var r=I(e);M.current.contains(r.target)&&g&&g(r),z(e)}}),[z]);return u((function(){var r;if(S instanceof HTMLElement&&M.current instanceof HTMLElement){var o={onScroll:"scroll",onWheel:"wheel"},c=M.current;return S.appendChild(M.current),n(r=t(o)).call(r,(function(r){var n=e(r,2),t=n[0],o=n[1];w[t]&&(A.current[t]=function(e){return w[t](I(e))},document.addEventListener(o,A.current[t]))})),document.addEventListener("keydown",q),document.addEventListener("mousedown",B),function(){var r;n(r=t(o)).call(r,(function(r){var n=e(r,2),t=n[0],o=n[1];w[t]&&(document.removeEventListener(o,A.current[t]),delete A.current[t])})),document.removeEventListener("keydown",q),document.removeEventListener("mousedown",B),S.removeChild(c)}}}),[z,q,S,M]),{isVisible:k.current,portalRef:M,ref:H,Portal:V,openPortal:R,closePortal:W}}
